
---

- name: Update cache
  apt:
    update_cache: yes

- name: Debian 9 (Stretch)
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")
  block:

    - name: Install Cyware indexer dependencies
      apt:
        name: [
          'unzip', 'wget', 'curl', 'apt-transport-https', software-properties-common
        ]
        state: present

- name: Add Cyware indexer repository
  block:
    - name: Add apt repository signing key
      apt_key:
        url: "{{ cyware_repo.gpg }}"
        state: present

    - name: Add Cyware indexer repository
      apt_repository:
        repo: "{{ cyware_repo.apt }}"
        state: present
        filename: 'cyware-indexer'
        update_cache: yes

- name: Install Cyware indexer
  apt:
    name: cyware-indexer={{ indexer_version }}-1
    state: present
  register: install
  tags: install