---
- name: restart cyware-agent
  service: name=cyware-agent state=restarted enabled=yes

- name: Windows | Restart Cyware Agent
  win_service: name=CywareSvc start_mode=auto state=restarted

- name: macOS | Restart Cyware Agent
  command: /Library/Ossec/bin/cyware-control restart