- name: Generate certificates prior to converging
  hosts: localhost
  become: true
  become_user: root
  roles:
    # 1. Check packages
    - role: ../../roles/cyware/check-packages
      become: no
      delegate_to: localhost
      run_once: true
    # 2. Generate certificates
    - role: ../../roles/cyware/cyware-indexer
      vars:
        generate_certs: true
        perform_installation: false
        instances:
          node1:
            name: cyware-es01       # Important: must be equal to indexer_node_name.
            ip: "127.0.0.1"   # When unzipping, the node will search for its node name folder to get the cert.
            role: indexer
          node3:
            name: cyware-mgr01
            ip: "127.0.0.1"
            role: cyware
          node5:
            name: cyware-dash01
            ip: "127.0.0.1"
            role: dashboard
  pre_tasks:
    - name: overview of cert configuration
      debug:
        var: cyware_endpoint_list

- name: Converge
  hosts: localhost
  become: true
  become_user: root
  roles:
    # 1. Cyware indexer
    - role: ../../roles/cyware/cyware-indexer
      vars:
        indexer_node_name: "cyware-es01"
        single_node: true
    # 2. Managers
    - role: ../../roles/cyware/ansible-cyware-manager
    - role: ../../roles/cyware/ansible-filebeat-oss
      vars:
        filebeat_node_name: "cyware-mgr01"
        filebeat_output_indexer_hosts:
        - "localhost:9200"
    # 3. Cyware dashboard
    - role: ../../roles/cyware/cyware-dashboard
      vars:
        dashboard_node_name: "cyware-dash01"
  vars:
    instances:
      node1:
        name: cyware-es01       # Important: must be equal to indexer_node_name.
        ip: "127.0.0.1"  # When unzipping, the node will search for its node name folder to get the cert.
        role: indexer
      node3:
        name: cyware-mgr01
        ip: "127.0.0.1"
        role: cyware
      node5:
        name: cyware-dash01
        ip: "127.0.0.1"
        role: dashboard