---
- hosts: managers
  roles:
    - role: ../roles/cyware/ansible-cyware-manager
    - role: ../roles/cyware/ansible-filebeat-oss
      filebeat_output_indexer_hosts:
      - "<indexer-node-1>:9200"
      - "<indexer-node-2>:9200"
      - "<indexer-node-2>:9200"
